/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedTreesRouteImport } from './routes/_authenticated/trees'
import { Route as AuthenticatedTreeIdBuildRouteImport } from './routes/_authenticated/tree.$id.build'
import { Route as AuthenticatedTreeIdNavigateRouteImport } from './routes/_authenticated/tree.$id.navigate'
import { Route as AuthenticatedTreeIdSettingsRouteImport } from './routes/_authenticated/tree.$id.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreesRoute = AuthenticatedTreesRouteImport.update({
  id: '/trees',
  path: '/trees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreeIdBuildRoute =
  AuthenticatedTreeIdBuildRouteImport.update({
    id: '/tree/$id/build',
    path: '/tree/$id/build',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreeIdNavigateRoute =
  AuthenticatedTreeIdNavigateRouteImport.update({
    id: '/tree/$id/navigate',
    path: '/tree/$id/navigate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreeIdSettingsRoute =
  AuthenticatedTreeIdSettingsRouteImport.update({
    id: '/tree/$id/settings',
    path: '/tree/$id/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/trees': typeof AuthenticatedTreesRoute
  '/tree/$id/build': typeof AuthenticatedTreeIdBuildRoute
  '/tree/$id/navigate': typeof AuthenticatedTreeIdNavigateRoute
  '/tree/$id/settings': typeof AuthenticatedTreeIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/trees': typeof AuthenticatedTreesRoute
  '/tree/$id/build': typeof AuthenticatedTreeIdBuildRoute
  '/tree/$id/navigate': typeof AuthenticatedTreeIdNavigateRoute
  '/tree/$id/settings': typeof AuthenticatedTreeIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/_authenticated/trees': typeof AuthenticatedTreesRoute
  '/_authenticated/tree/$id/build': typeof AuthenticatedTreeIdBuildRoute
  '/_authenticated/tree/$id/navigate': typeof AuthenticatedTreeIdNavigateRoute
  '/_authenticated/tree/$id/settings': typeof AuthenticatedTreeIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/profile'
    | '/templates'
    | '/trash'
    | '/trees'
    | '/tree/$id/build'
    | '/tree/$id/navigate'
    | '/tree/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/favorites'
    | '/profile'
    | '/templates'
    | '/trash'
    | '/trees'
    | '/tree/$id/build'
    | '/tree/$id/navigate'
    | '/tree/$id/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/_authenticated/profile'
    | '/_authenticated/templates'
    | '/_authenticated/trash'
    | '/_authenticated/trees'
    | '/_authenticated/tree/$id/build'
    | '/_authenticated/tree/$id/navigate'
    | '/_authenticated/tree/$id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trees': {
      id: '/_authenticated/trees'
      path: '/trees'
      fullPath: '/trees'
      preLoaderRoute: typeof AuthenticatedTreesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tree/$id/build': {
      id: '/_authenticated/tree/$id/build'
      path: '/tree/$id/build'
      fullPath: '/tree/$id/build'
      preLoaderRoute: typeof AuthenticatedTreeIdBuildRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tree/$id/navigate': {
      id: '/_authenticated/tree/$id/navigate'
      path: '/tree/$id/navigate'
      fullPath: '/tree/$id/navigate'
      preLoaderRoute: typeof AuthenticatedTreeIdNavigateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tree/$id/settings': {
      id: '/_authenticated/tree/$id/settings'
      path: '/tree/$id/settings'
      fullPath: '/tree/$id/settings'
      preLoaderRoute: typeof AuthenticatedTreeIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedTreesRoute: typeof AuthenticatedTreesRoute
  AuthenticatedTreeIdBuildRoute: typeof AuthenticatedTreeIdBuildRoute
  AuthenticatedTreeIdNavigateRoute: typeof AuthenticatedTreeIdNavigateRoute
  AuthenticatedTreeIdSettingsRoute: typeof AuthenticatedTreeIdSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedTreesRoute: AuthenticatedTreesRoute,
  AuthenticatedTreeIdBuildRoute: AuthenticatedTreeIdBuildRoute,
  AuthenticatedTreeIdNavigateRoute: AuthenticatedTreeIdNavigateRoute,
  AuthenticatedTreeIdSettingsRoute: AuthenticatedTreeIdSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
